### ISSUE TITLE
Error while running install_piksi_multi.sh

### ISSUE THREAD

**Issue by saeedarabi92** [ethz-asl/ethz_piksi_ros#175]
I am facing a lot of error while installing the driver on my jetson TX2. Could you help me with finding the solution?

```
nvidia@saeed:~/Documents/swift_ros_ws/src/ethz_piksi_ros/piksi_multi_rtk_ros/install$ ./install_piksi_multi.sh
 
Installing SBP library for Piksi Multi.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pip is already the newest version (9.0.1-2.3~ubuntu1.18.04.1).
0 upgraded, 0 newly installed, 0 to remove and 559 not upgraded.
WARNING: The directory '/home/nvidia/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting sbp==v2.6.5
  Downloading sbp-2.6.5-py2.py3-none-any.whl (193 kB)
     |█▊                              | 10 kB 6.0 M     |███▍                            | 20 kB 3.3 M     |█████                           | 30 kB 4.2 M     |██████▉                         | 40 kB 3.1 M     |████████▌                       | 51 kB 3.0 M     |██████████▏                     | 61 kB 3.2 M     |███████████▉                    | 71 kB 3.5 M     |█████████████▋                  | 81 kB 3.4 M     |███████████████▎                | 92 kB 3.2 M     |█████████████████               | 102 kB 3.1      |██████████████████▊             | 112 kB 3.1      |████████████████████▍           | 122 kB 3.1      |██████████████████████          | 133 kB 3.1      |███████████████████████▊        | 143 kB 3.1      |█████████████████████████▌      | 153 kB 3.1      |███████████████████████████▏    | 163 kB 3.1      |████████████████████████████▉   | 174 kB 3.1      |██████████████████████████████▌ | 184 kB 3.1      |████████████████████████████████| 193 kB 3.1 MB/s 
Requirement already satisfied: pylibftdi in /usr/local/lib/python3.6/dist-packages (from sbp==v2.6.5) (0.16.1.2)
Requirement already satisfied: requests==2.20.* in /usr/local/lib/python3.6/dist-packages (from sbp==v2.6.5) (2.20.0)
Collecting numpy==1.16.*
  Downloading numpy-1.16.6.zip (5.1 MB)
     |                                | 10 kB 6.6 M     |▏                               | 20 kB 6.7 M     |▏                               | 30 kB 7.0 M     |▎                               | 40 kB 7.6 M     |▎                               | 51 kB 7.9 M     |▍                               | 61 kB 6.9 M     |▌                               | 71 kB 6.5 M     |▌                               | 81 kB 5.7 M     |▋                               | 92 kB 5.6 M     |▋                               | 102 kB 5.6      |▊                               | 112 kB 5.6      |▊                               | 122 kB 5.6      |▉                               | 133 kB 5.6      |█                               | 143 kB 5.6      |█                               | 153 kB 5.6      |█                               | 163 kB 5.6      |█                               | 174 kB 5.6      |█▏                              | 184 kB 5.6      |█▏                              | 194 kB 5.6      |█▎                              | 204 kB 5.6      |█▍                              | 215 kB 5.6      |█▍                              | 225 kB 5.6      |█▌                              | 235 kB 5.6      |█▌                              | 245 kB 5.6      |█▋                              | 256 kB 5.6      |█▋                              | 266 kB 5.6      |█▊                              | 276 kB 5.6      |█▉                              | 286 kB 5.6      |█▉                              | 296 kB 5.6      |██                              | 307 kB 5.6      |██                              | 317 kB 5.6      |██                              | 327 kB 5.6      |██                              | 337 kB 5.6      |██▏                             | 348 kB 5.6      |██▎                             | 358 kB 5.6      |██▎                             | 368 kB 5.6      |██▍                             | 378 kB 5.6      |██▍                             | 389 kB 5.6      |██▌                             | 399 kB 5.6      |██▌                             | 409 kB 5.6      |██▋                             | 419 kB 5.6      |██▊                             | 430 kB 5.6      |██▊                             | 440 kB 5.6      |██▉                             | 450 kB 5.6      |██▉                             | 460 kB 5.6      |███                             | 471 kB 5.6      |███                             | 481 kB 5.6      |███                             | 491 kB 5.6      |███▏                            | 501 kB 5.6      |███▏                            | 512 kB 5.6      |███▎                            | 522 kB 5.6      |███▎                            | 532 kB 5.6      |███▍                            | 542 kB 5.6      |███▍                            | 552 kB 5.6      |███▌                            | 563 kB 5.6      |███▋                            | 573 kB 5.6      |███▋                            | 583 kB 5.6      |███▊                            | 593 kB 5.6      |███▊                            | 604 kB 5.6      |███▉                            | 614 kB 5.6      |███▉                            | 624 kB 5.6      |████                            | 634 kB 5.6      |████                            | 645 kB 5.6      |████                            | 655 kB 5.6      |████▏                           | 665 kB 5.6      |████▏                           | 675 kB 5.6      |████▎                           | 686 kB 5.6      |████▎                           | 696 kB 5.6      |████▍                           | 706 kB 5.6      |████▌                           | 716 kB 57 k     |████▌                           | 727 kB 57 k     |████▋                           | 737 kB 57 k     |████▋                           | 747 kB 57 k     |████▊                           | 757 kB 57 k     |████▉                           | 768 kB 57 k     |████▉                           | 778 kB 57 k     |█████                           | 788 kB 57 k     |█████                           | 798 kB 57 k     |█████                           | 808 kB 57 k     |█████                           | 819 kB 57 k     |█████▏                          | 829 kB 57 k     |█████▎                          | 839 kB 57 k     |█████▎                          | 849 kB 57 k     |█████▍                          | 860 kB 57 k     |█████▍                          | 870 kB 57 k     |█████▌                          | 880 kB 57 k     |█████▌                          | 890 kB 57 k     |█████▋                          | 901 kB 57 k     |█████▊                          | 911 kB 57 k     |█████▊                          | 921 kB 57 k     |█████▉                          | 931 kB 57 k     |█████▉                          | 942 kB 57 k     |██████                          | 952 kB 57 k     |██████                          | 962 kB 57 k     |██████                          | 972 kB 57 k     |██████▏                         | 983 kB 57 k     |██████▏                         | 993 kB 57 k     |██████▎                         | 1.0 MB 57 k     |██████▎                         | 1.0 MB 57 k     |██████▍                         | 1.0 MB 57 k     |██████▍                         | 1.0 MB 57 k     |██████▌                         | 1.0 MB 57 k     |██████▋                         | 1.1 MB 57 k     |██████▋                         | 1.1 MB 57 k     |██████▊                         | 1.1 MB 57 k     |██████▊                         | 1.1 MB 57 k     |██████▉                         | 1.1 MB 57 k     |██████▉                         | 1.1 MB 57 k     |███████                         | 1.1 MB 57 k     |███████                         | 1.1 MB 57 k     |███████                         | 1.1 MB 57 k     |███████▏                        | 1.1 MB 57 k     |███████▏                        | 1.2 MB 57 k     |███████▎                        | 1.2 MB 57 k     |███████▎                        | 1.2 MB 57 k     |███████▍                        | 1.2 MB 57 k     |███████▌                        | 1.2 MB 57 k     |███████▌                        | 1.2 MB 57 k     |███████▋                        | 1.2 MB 57 k     |███████▋                        | 1.2 MB 57 k     |███████▊                        | 1.2 MB 57 k     |███████▊                        | 1.2 MB 57 k     |███████▉                        | 1.3 MB 57 k     |████████                        | 1.3 MB 57 k     |████████                        | 1.3 MB 57 k     |████████                        | 1.3 MB 57 k     |████████                        | 1.3 MB 57 k     |████████▏                       | 1.3 MB 57 k     |████████▏                       | 1.3 MB 57 k     |████████▎                       | 1.3 MB 57 k     |████████▍                       | 1.3 MB 57 k     |████████▍                       | 1.4 MB 57 k     |████████▌                       | 1.4 MB 57 k     |████████▌                       | 1.4 MB 57 k     |████████▋                       | 1.4 MB 57 k     |████████▋                       | 1.4 MB 57 k     |████████▊                       | 1.4 MB 57 k     |████████▉                       | 1.4 MB 57 k     |████████▉                       | 1.4 MB 57 k     |█████████                       | 1.4 MB 57 k     |█████████                       | 1.4 MB 57 k     |█████████                       | 1.5 MB 57 k     |█████████                       | 1.5 MB 57 k     |█████████▏                      | 1.5 MB 57 k     |█████████▎                      | 1.5 MB 57 k     |█████████▎                      | 1.5 MB 57 k     |█████████▍                      | 1.5 MB 57 k     |█████████▍                      | 1.5 MB 57 k     |█████████▌                      | 1.5 MB 57 k     |█████████▋                      | 1.5 MB 57 k     |█████████▋                      | 1.5 MB 57 k     |█████████▊                      | 1.6 MB 57 k     |█████████▊                      | 1.6 MB 57 k     |█████████▉                      | 1.6 MB 57 k     |█████████▉                      | 1.6 MB 57 k     |██████████                      | 1.6 MB 57 k     |████████████████████████████████| 5.1 MB 58 kB/s 
Requirement already satisfied: pyserial in /usr/local/lib/python3.6/dist-packages (from sbp==v2.6.5) (3.4)
Requirement already satisfied: pyftdi==0.13.* in /usr/local/lib/python3.6/dist-packages (from sbp==v2.6.5) (0.13.4)
Requirement already satisfied: construct==2.9.33 in /usr/local/lib/python3.6/dist-packages (from sbp==v2.6.5) (2.9.33)
Collecting pybase64
  Downloading pybase64-1.0.1.tar.gz (81 kB)
     |████████████████████████████████| 81 kB 11.9 MB/s 
Collecting ujson
  Downloading ujson-3.0.0.tar.gz (7.1 MB)
     |████████████████████████████████| 7.1 MB 125 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests==2.20.*->sbp==v2.6.5) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests==2.20.*->sbp==v2.6.5) (2020.6.20)
Collecting urllib3<1.25,>=1.21.1
  Downloading urllib3-1.24.3-py2.py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 2.9 MB/s 
Requirement already satisfied: idna<2.8,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests==2.20.*->sbp==v2.6.5) (2.7)
Requirement already satisfied: pyusb>=1.0.0b1 in /usr/local/lib/python3.6/dist-packages (from pyftdi==0.13.*->sbp==v2.6.5) (1.0.2)
Requirement already satisfied: six in /home/nvidia/.local/lib/python3.6/site-packages (from pyftdi==0.13.*->sbp==v2.6.5) (1.15.0)
Building wheels for collected packages: numpy, pybase64, ujson
  Building wheel for numpy (setup.py) ... done
  Created wheel for numpy: filename=numpy-1.16.6-cp36-cp36m-linux_aarch64.whl size=10143579 sha256=1eb659f81b5a6a0d90d1599cf6b5e869f96ebe828b027b45f14c6f7b718418be
  Stored in directory: /tmp/pip-ephem-wheel-cache-ux8qg0wh/wheels/a0/b9/1f/f8feb5df5522241dc4f4cebbf7b5c4464bf7491849e0fa8c35
  Building wheel for pybase64 (setup.py) ... done
  Created wheel for pybase64: filename=pybase64-1.0.1-cp36-cp36m-linux_aarch64.whl size=49289 sha256=c62125880eb3e29733abdd3511c3da1a168b7c5bbbf2c509def03aa7cedc75dd
  Stored in directory: /tmp/pip-ephem-wheel-cache-ux8qg0wh/wheels/29/d1/22/5592105d0657d68cd1761765cf9007fa4620e0d311f3be44e1
  Building wheel for ujson (PEP 517) ... done
  Created wheel for ujson: filename=ujson-3.0.0-cp36-cp36m-linux_aarch64.whl size=169815 sha256=bcfc7be8bc74d4e62e9e65ecfef978e1175338e44be573184cff33056651d666
  Stored in directory: /tmp/pip-ephem-wheel-cache-ux8qg0wh/wheels/f5/f6/03/29c719e2e47b54e58e399598e5f630d50bcef8f60885bbf9c4
Successfully built numpy pybase64 ujson
ERROR: botocore 1.17.15 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
ERROR: awscli 1.18.92 has requirement docutils<0.16,>=0.10, but you'll have docutils 0.16 which is incompatible.
ERROR: uff 0.6.5 has requirement protobuf>=3.3.0, but you'll have protobuf 3.0.0 which is incompatible.
Installing collected packages: numpy, pybase64, ujson, sbp, urllib3
  Attempting uninstall: numpy
    Found existing installation: numpy 1.18.4
    Uninstalling numpy-1.18.4:
      Successfully uninstalled numpy-1.18.4
  Attempting uninstall: sbp
    Found existing installation: sbp 2.7.3
    Uninstalling sbp-2.7.3:
      Successfully uninstalled sbp-2.7.3
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.25.9
    Uninstalling urllib3-1.25.9:
      Successfully uninstalled urllib3-1.25.9
Successfully installed numpy-1.19.0 pybase64-1.0.1 sbp-2.6.5 ujson-3.0.0 urllib3-1.24.3
WARNING: The directory '/home/nvidia/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting llvmlite
  Downloading llvmlite-0.33.0.tar.gz (104 kB)
     |████████████████████████████████| 104 kB 992 kB/s 
Building wheels for collected packages: llvmlite
  Building wheel for llvmlite (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-d1rn56sv
       cwd: /tmp/pip-install-5g62hi5r/llvmlite/
  Complete output (26 lines):
  running bdist_wheel
  /usr/bin/python3 /tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py
  LLVM version... Traceback (most recent call last):
    File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 105, in main_posix
      out = subprocess.check_output([llvm_config, '--version'])
    File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
      **kwargs).stdout
    File "/usr/lib/python3.6/subprocess.py", line 423, in run
      with Popen(*popenargs, **kwargs) as process:
    File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
      restore_signals, start_new_session)
    File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
      raise child_exception_type(errno_num, err_msg, err_filename)
  FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 191, in <module>
      main()
    File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 181, in main
      main_posix('linux', '.so')
    File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 108, in main_posix
      "to the path for llvm-config" % (llvm_config,))
  RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
  error: command '/usr/bin/python3' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for llvmlite
  Running setup.py clean for llvmlite
Failed to build llvmlite
Installing collected packages: llvmlite
    Running setup.py install for llvmlite ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ftb8j14o/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite
         cwd: /tmp/pip-install-5g62hi5r/llvmlite/
    Complete output (29 lines):
    running install
    running build
    got version from file /tmp/pip-install-5g62hi5r/llvmlite/llvmlite/_version.py {'version': '0.33.0', 'full': '76c8ecba36e23fa8b6878505a1afc8a3d7a2c8a1'}
    running build_ext
    /usr/bin/python3 /tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.6/subprocess.py", line 423, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config': 'llvm-config'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 191, in <module>
        main()
      File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 181, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-5g62hi5r/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/usr/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5g62hi5r/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ftb8j14o/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.6/llvmlite Check the logs for full command output.
SBP Library Installed
Installing ROS node requirements.
WARNING: The directory '/home/nvidia/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting numpy-quaternion
  Downloading numpy-quaternion-2020.5.19.15.27.24.tar.gz (51 kB)
     |████████████████████████████████| 51 kB 1.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: numpy>=1.13 in /usr/local/lib/python3.6/dist-packages (from numpy-quaternion) (1.19.0)
Building wheels for collected packages: numpy-quaternion
  Building wheel for numpy-quaternion (PEP 517) ... done
  Created wheel for numpy-quaternion: filename=numpy_quaternion-2020.5.19.15.27.24-cp36-cp36m-linux_aarch64.whl size=146768 sha256=13584a1ac713430bbb7f43e95923d64f34cf27b3e7aceb377c824ee0e893df3b
  Stored in directory: /tmp/pip-ephem-wheel-cache-lyqcwuaw/wheels/4d/0a/a6/061784c65037879cb196908ace85600ae19174d6289422faa2
Successfully built numpy-quaternion
Installing collected packages: numpy-quaternion
Successfully installed numpy-quaternion-2020.5.19.15.27.24
WARNING: The directory '/home/nvidia/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scipy
  Downloading scipy-1.5.0.tar.gz (25.6 MB)
     |████████████████████████████████| 25.6 MB 61 kB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpiaf262vn
         cwd: /tmp/pip-install-sfj_lhtx/scipy
    Complete output (140 lines):
    lapack_opt_info:
    lapack_mkl_info:
    customize UnixCCompiler
      libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    openblas_lapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    openblas_clapack_info:
    customize UnixCCompiler
    customize UnixCCompiler
      libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
    customize UnixCCompiler
      libraries tatlas,tatlas not found in /usr/lib/aarch64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE
    
    atlas_3_10_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
    customize UnixCCompiler
      libraries satlas,satlas not found in /usr/lib/aarch64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE
    
    atlas_threads_info:
    Setting PTATLAS=ATLAS
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
    customize UnixCCompiler
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/aarch64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE
    
    atlas_info:
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/local/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib
    customize UnixCCompiler
      libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
    customize UnixCCompiler
      libraries f77blas,cblas,atlas not found in /usr/lib/aarch64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE
    
    accelerate_info:
      NOT AVAILABLE
    
    lapack_info:
    customize UnixCCompiler
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
      NOT AVAILABLE
    
    lapack_src_info:
      NOT AVAILABLE
    
      NOT AVAILABLE
    
    setup.py:462: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-571e6azn'), proceeding with generating Cython sources and expanding templates
      ' '.join(sys.argv[1:])))
    Running from SciPy source directory.
    /usr/local/lib/python3.6/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    /usr/local/lib/python3.6/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    /usr/local/lib/python3.6/dist-packages/numpy/distutils/system_info.py:639: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 157, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 249, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/usr/local/lib/python3.6/dist-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 583, in <module>
        setup_package()
      File "setup.py", line 579, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.6/dist-packages/numpy/distutils/core.py", line 137, in setup
        config = configuration()
      File "setup.py", line 477, in configuration
        raise NotFoundError(msg)
    numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpiaf262vn Check the logs for full command output.
WARNING: The directory '/home/nvidia/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyproj
  Downloading pyproj-2.6.1.post1.tar.gz (545 kB)
     |████████████████████████████████| 545 kB 4.3 MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmps8x7_lr1
       cwd: /tmp/pip-install-d5uxig0_/pyproj
  Complete output (1 lines):
  ERROR: Minimum supported proj version is 6.2.0, installed version is 4.9.3. For more information see: https://pyproj4.github.io/pyproj/stable/installation.html
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /usr/local/lib/python3.6/dist-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmps8x7_lr1 Check the logs for full command output.
User nvidia is already included in 'dialout' group.
 
Installation completed.

```

**Comment by saeedarabi92** [comment]
The fix was to build some packages (llvm, proj, ... ) from the source.
Closing this.
