### ISSUE TITLE
Not able to Launch piksi_multi_rtk_ros node

### ISSUE THREAD

**Issue by GeoBIMpro** [ethz-asl/ethz_piksi_ros#61]
Hi, I am using latest Firmware (2.1.14) for Piksi Multi.
I have edited "install_piksi_multi.sh" to get latest libsbp(v2.4.1)
Getting below error while launching.

root@vasanthaw:~/catkin_ws# roslaunch piksi_multi_rtk_ros piksi_multi_rover.launch
... logging to /root/.ros/log/379bb058-d9f6-11e8-978e-b0359ff62f07/roslaunch-vasanthaw-8529.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://vasanthaw:35059/

SUMMARY
========

PARAMETERS
 * /piksi/base_station_ip_for_latency_estimation: 192.168.0.1
 * /piksi/base_station_mode: False
 * /piksi/baud_rate: 115200
 * /piksi/broadcast_addr: 192.168.0.255
 * /piksi/broadcast_port: 26078
 * /piksi/debug_mode: True
 * /piksi/driver_verbose: True
 * /piksi/interface: serial
 * /piksi/navsatfix_frame_id: base_link
 * /piksi/publish_raw_imu_and_mag: False
 * /piksi/serial_port: /dev/ttyUSB0
 * /piksi/tcp_addr: 192.168.0.222
 * /piksi/tcp_port: 55555
 * /piksi/var_rtk_fix: [0.0049, 0.0049, ...
 * /piksi/var_rtk_float: [25.0, 25.0, 64.0]
 * /piksi/var_spp: [25.0, 25.0, 64.0]
 * /piksi/var_spp_sbas: [1.0, 1.0, 1.0]
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    piksi (piksi_multi_rtk_ros/piksi_multi)

auto-starting new master
process[master]: started with pid [8542]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 379bb058-d9f6-11e8-978e-b0359ff62f07
process[rosout-1]: started with pid [8557]
started core service [/rosout]
process[piksi-2]: started with pid [8573]
/usr/local/lib/python2.7/dist-packages/requests-2.20.0-py2.7.egg/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
[INFO] [1540651216.898651]: /piksi start
Traceback (most recent call last):
  File "/root/catkin_ws/src/ethz_piksi_ros/piksi_multi_rtk_ros/bin/piksi_multi", line 6, in <module>
    piksi_multi = PiksiMulti()
  File "/root/catkin_ws/src/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py", line 74, in __init__
    installed_sbp_version = self.get_installed_sbp_version()
  File "/root/catkin_ws/src/ethz_piksi_ros/piksi_multi_rtk_ros/src/piksi_multi_rtk_ros/piksi_multi.py", line 1056, in get_installed_sbp_version
    pip_show_output = subprocess.Popen(command, stdout=subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
[piksi-2] process has died [pid 8573, exit code 1, cmd /root/catkin_ws/src/ethz_piksi_ros/piksi_multi_rtk_ros/bin/piksi_multi __name:=piksi __log:=/root/.ros/log/379bb058-d9f6-11e8-978e-b0359ff62f07/piksi-2.log].
log file: /root/.ros/log/379bb058-d9f6-11e8-978e-b0359ff62f07/piksi-2*.log

**Comment by GeoBIMpro** [comment]
Sorry, Solved the issue. libsbp was not installed properly.
